[global]
log_level = 'info'
strategy = 'all'

[[chains]]
account_prefix = 'cosmos'
clock_drift = '5s'
fee_amount = 10
fee_denom = 'stake'
gas = 3000000
grpc_addr = 'http://127.0.0.1:8090'
id = 'test-1'
key_name = 'testkey'
rpc_addr = 'http://127.0.0.1:16657'
rpc_timeout = '10s'
store_prefix = 'ibc'
trusting_period = '14days'
websocket_addr = 'ws://127.0.0.1:16657/websocket'

[chains.trust_threshold]
denominator = '3'
numerator = '1'

[[chains]]
account_prefix = 'cosmos'
clock_drift = '5s'
fee_amount = 1000
fee_denom = 'stake'
gas = 3000000
grpc_addr = 'http://127.0.0.1:9090'
id = 'test-2'
key_name = 'testkey'
rpc_addr = 'http://127.0.0.1:26657'
rpc_timeout = '10s'
store_prefix = 'ibc'
trusting_period = '14days'
websocket_addr = 'ws://127.0.0.1:26657/websocket'

[chains.trust_threshold]
denominator = '3'
numerator = '1'
