name: Compatibility E2E

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORG: cosmos
  IMAGE_NAME: ibc-go-icad

jobs:
  # v0.1.x / ibc-go v3
  ica-chain-a-v0-1-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.1.x
      test-suite: ica-chain-a

  ica-chain-b-v0-1-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.1.x
      test-suite: ica-chain-b

  # v0.2.x / ibc-go v4
  ica-chain-a-v0-2-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.2.x
      test-suite: ica-chain-a

  ica-chain-b-v0-2-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.2.x
      test-suite: ica-chain-b

  incentivized-ica-chain-a-v0-2-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.2.x
      test-suite: incentivized-ica-chain-a

  incentivized-ica-chain-b-v0-2-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.2.x
      test-suite: incentivized-ica-chain-b

  # v0.3.x / ibc-go v5
  ica-chain-a-v0-3-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.3.x
      test-suite: ica-chain-a

  ica-chain-b-v0-3-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.3.x
      test-suite: ica-chain-b

  incentivized-ica-chain-a-v0-3-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.3.x
      test-suite: incentivized-ica-chain-a

  incentivized-ica-chain-b-v0-3-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.3.x
      test-suite: incentivized-ica-chain-b

  # v0.4.x / ibc-go v6
  ica-chain-a-v0-4-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.4.x
      test-suite: ica-chain-a

  ica-chain-b-v0-4-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.4.x
      test-suite: ica-chain-b

  incentivized-ica-chain-a-v0-4-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.4.x
      test-suite: incentivized-ica-chain-a

  incentivized-ica-chain-b-v0-4-x:
    uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
    with:
      test-file-directory: v0.4.x
      test-suite: incentivized-ica-chain-b
