name: Compatibility E2E

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io
  ORG: cosmos
  IMAGE_NAME: ibc-go-icad

jobs:
  ica-chain-a:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - v0.1.x # ibc-go v3
          - v0.2.x # ibc-go v4
          - v0.3.x # ibc-go v5
          - v0.4.x # ibc-go v6
    steps:
    - uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
      with:
        test-file-directory: ${{ matrix.branch }}
        test-suite: ica-chain-a

  ica-chain-b:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - v0.1.x # ibc-go v3
          - v0.2.x # ibc-go v4
          - v0.3.x # ibc-go v5
          - v0.4.x # ibc-go v6
    steps:
      - uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
        with:
          test-file-directory: ${{ matrix.branch }}
          test-suite: ica-chain-b

  incentivized-ica-chain-a:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - v0.1.x # ibc-go v3
          - v0.2.x # ibc-go v4
          - v0.3.x # ibc-go v5
          - v0.4.x # ibc-go v6
    steps:
      - uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
        with:
          test-file-directory: ${{ matrix.branch }}
          test-suite: incentivized-ica-chain-a

  incentivized-ica-chain-b:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - v0.1.x # ibc-go v3
          - v0.2.x # ibc-go v4
          - v0.3.x # ibc-go v5
          - v0.4.x # ibc-go v6
    steps:
      - uses: cosmos/ibc-go/.github/workflows/e2e-compatibility-workflow-call.yaml@main
        with:
          test-file-directory: ${{ matrix.branch }}
          test-suite: incentivized-ica-chain-b
